name: Huseyin Kombayci
title: Full Stack Software Developer
description: I build apps, CLIs and APIs.
baseurl: ''
url: https://huseyinkombayci.com
social-link: huseyinkombayci

exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - license
  - CNAME
  - screenshot.jpg
plugins:
  - jekyll-sitemap
